<a href="https://colab.research.google.com/github/Poorva48/Cryptography_Assignment1/blob/main/CRYPTOGRAPHY_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sympy import Matrix


def prepare_text(text, n):
    text = "".join([c.upper() for c in text if c.isalpha()])

    while len(text) % n != 0:
        text += "X"

    return text


def encrypt_hill(plaintext, key_matrix):
    n = key_matrix.shape[0]

    text = prepare_text(plaintext, n)
    ciphertext = ""

    for i in range(0, len(text), n):

        block = [ord(c) - 65 for c in text[i:i+n]]

        P = np.array(block).reshape(n, 1)

        C = np.dot(key_matrix, P) % 26

        for val in C.flatten():
            ciphertext += chr(int(val) + 65)

    return ciphertext


def decrypt_hill(ciphertext, key_matrix):
    n = key_matrix.shape[0]

    try:
        inv_matrix = np.array(
            Matrix(key_matrix).inv_mod(26)
        ).astype(int)

    except ValueError:
        return "Error: Key matrix is not invertible modulo 26."

    plaintext = ""

    for i in range(0, len(ciphertext), n):

        block = [ord(c) - 65 for c in ciphertext[i:i+n]]

        C = np.array(block).reshape(n, 1)

        P = np.dot(inv_matrix, C) % 26

        for val in P.flatten():
            plaintext += chr(int(val) + 65)

    return plaintext


print("=== Hill Cipher Tool ===")

K = np.array([
    [6, 24, 1],
    [13, 16, 10],
    [20, 17, 15]
])

message = input("Enter plaintext: ")

print("\nKey Matrix:")
print(K)

print("Plaintext:", message)

encrypted = encrypt_hill(message, K)
print("\n[+] Encrypted Text:", encrypted)

decrypted = decrypt_hill(encrypted, K)
print("[+] Decrypted Text:", decrypted)


=== Hill Cipher Tool ===
Enter plaintext: hill cipher

Key Matrix:
[[ 6 24  1]
 [13 16 10]
 [20 17 15]]
Plaintext: hill cipher

[+] Encrypted Text: LRZSVKCJLBNK
[+] Decrypted Text: HILLCIPHERXX
